const message = {
  isExisted: 'Dữ liệu đã tồn tại',
  notFound: 'Không tìm thấy',
  notEmpty: 'Không được để trống',
  isInt: (min, max) =>
    `Phải là kiểu số nguyên${min && max ? ` từ ${min} đến ${max}` : min ? ` lớn hơn hoặc bằng ${min}` : max ? ` nhỏ hơn hoặc bằng ${max}` : ''}`,
  isLength: (min, max) => `${min && max ? `Từ ${min} - ${max} kí tự` : min ? `Lớn hơn ${min} kí tự` : max ? `Nhỏ hơn ${max} kí tự` : ''}`,
  isIn: (values) => `Chỉ cho phép các giá trị: ${values.join(', ')}`,
  isString: 'Phải là kiểu kí tự',
  isNumeric: 'Phải là kiểu số',
  isArray: 'Phải là kiểu mảng',
  isEmail: 'Sai định dạng email',
  incorrectPassword: 'Mật khẩu không đúng',
  unauthenticated: 'Chưa được xác thực',
  invalidToken: 'Token không hợp lệ',
  jwtHasExpiredPleaseLoginAgain: 'Token đã hết hạn. Vui lòng đăng nhập lại',
  invalid: 'Không hợp lệ',
  duplicate: 'Trùng lặp giá trị',
  notExist: 'Dữ liệu không tồn tại',
  isObject: 'Dữ liệu phải là kiểu Object',
  invalidPhone: 'Số điện thoại không hợp lệ',
  min: (min) => `Nhỏ nhất là: ${min}`,
  invalidDate: 'Ngày không hợp lệ',
  getSuccessfully: 'Lấy thành công',
  createdSuccessfully: 'Thêm thành công',
  createdFailure: 'Thêm thất bại',
  updatedSuccessfully: 'Cập nhật thành công',
  updatedFailure: 'Cập nhật thất bại',
  deletedSuccessfully: 'Xóa thành công',
  deletedFailure: 'Xóa thất bại',
  loginSuccessfully: 'Đăng nhập thành công',
  logoutSuccessfully: 'Đăng xuất thành công',
  youDoNotHaveAccess: 'Bạn không có quyền truy cập',
  isStrongPassword: 'Mật khẩu phải chứa ít nhất 8 ký tự bao gồm tối thiểu có 1 ký tự đặt biệt, 1 số, 1 chữ cái IN HOA và 1 chữ cái thường',
  isFloat: (min, max) =>
    `Phải là kiểu số thực${min && max ? ` từ ${min} đến ${max}` : min ? ` lớn hơn hoặc bằng ${min}` : max ? ` nhỏ hơn hoặc bằng ${max}` : ''}`,
  forbidden: 'Không có quyền chỉnh sửa',
  badRequestPost: 'Tiêu đề và nội dung là bắt buộc',
  fileRequired: 'Phải có file đính kèm',
  fileTooLarge: 'Chỉ được up file 2mb',
  CharacterLimitExceeded: 'Ký tự vượt quá giới hạn cho phép'
}

module.exports = { message }
